config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :artists, only: [:index, :show]
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id          :integer          not null, primary key
#  name        :string
#  image_url   :string
#  released_at :date
#  artist_id   :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Album < ApplicationRecord
  belongs_to :artist
  has_many :songs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
# == Schema Information
#
# Table name: artists
#
#  id         :integer          not null, primary key
#  name       :string
#  image_url  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Artist < ApplicationRecord
  has_many :albums
end

app/models/song.rb
# == Schema Information
#
# Table name: songs
#
#  id          :integer          not null, primary key
#  name        :string
#  number      :integer
#  preview_url :string
#  album_id    :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Song < ApplicationRecord
  belongs_to :album
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/index.html.erb
<div class="container" >
  <div class="row">
    <div class="col-md-12">
        <% @artists.each do |artist|%>
          <div class="col-sm-6 col-md-4">
              <div class="thumbnail">
                <%= image_tag artist.image_url, class: 'image-responsive'%>
                <div class="caption">
                  <h3><%=artist.name%> </h3>
                  <p><%= link_to 'Ver mas', artist_path(id: artist.id),method: :get, class: 'btn btn-primary' %></p>
                </div>
              </div>
          </div>
        <%end%>
    </div>
  </div>
</div>

app/views/artists/show.html.erb
<div class="container" >
  <div class="row">
    <div class="col-md-8">
      <h1><%= @artist.name %></h1>
      <h3>Albums(<%= @artist.albums.count %>)</h3>
        <% @artist.albums.each do |album|%>
          <div class="col-sm-3 col-md-3">
              <div class="thumbnail">
                <%= image_tag album.image_url, class: 'image-responsive'%>
                <div class="caption">
                  <h3><%=album.name%> </h3>
                  <p><%= album.released_at %></p>
                </div>
              </div>
          </div>
        <%end%>
    </div>
    <div class="col-md-4">
      <%= image_tag @artist.image_url, class: 'image-responsive'%>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">Real Music</a>
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
      </div>
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Artistas', artists_path,method: :get %></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Mi cuenta <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Preferencias</a></li>
          </ul>
        </li>
        <li><a href="#">About</a></li>
      </ul>
		</div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <%= yield %>
  </body>
</html>